/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expense_management.java;

import expense_management.java.domain.Staff;
import expense_management.java.dto.CreateExpenseRequest;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class CreateForm extends javax.swing.JFrame {

    CreateExpenseRequest createRequest = new CreateExpenseRequest();
    Staff staff = new Staff();

    /**
     * Creates new form CreateForm
     */
    public CreateForm() {
        initComponents();
        inputAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();

                if (!Character.isDigit(c) && c != '.') {
                    evt.consume();
                }

                if (c == '.' && inputAmount.getText().contains(".")) {
                    evt.consume();
                }
            }
        });
        getStaffs();
    }

    public void getStaffs() {
        String url = "jdbc:mysql://localhost:3306/db_java_v1";
        String userDb = "root";
        String passDb = "";

        try (Connection cont = DriverManager.getConnection(url, userDb, passDb)) {

            String query = "SELECT staff.s_id, staff.s_name FROM staff";

            PreparedStatement stmt = cont.prepareStatement(query);

            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                inputStaff.addItem(rs.getString("s_name"));
            }

        } catch (SQLException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inputAmount = new javax.swing.JTextField();
        labelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescription = new javax.swing.JTextArea();
        inputStaff = new javax.swing.JComboBox<>();
        btnToChooseImage = new javax.swing.JButton();
        labelDate = new javax.swing.JLabel();
        labelAmount = new javax.swing.JLabel();
        lableStaff = new javax.swing.JLabel();
        lableImage = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lalImage = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createTitle.setText("Create New Expense");

        inputAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAmountActionPerformed(evt);
            }
        });

        labelDescription.setText("Description");

        inputDescription.setColumns(20);
        inputDescription.setRows(5);
        jScrollPane1.setViewportView(inputDescription);

        inputStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStaffActionPerformed(evt);
            }
        });

        btnToChooseImage.setText("Choose Image");
        btnToChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToChooseImageActionPerformed(evt);
            }
        });

        labelDate.setText("Datetime");

        labelAmount.setText("Amount");

        lableStaff.setText("Staff");

        lableImage.setText("Image");

        btnCreate.setBackground(new java.awt.Color(0, 255, 51));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lalImage.setText("Image File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDate)
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelAmount)
                                .addComponent(inputAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lableStaff, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputStaff, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToChooseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lalImage)
                            .addComponent(lableImage))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDate)
                    .addComponent(labelAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableStaff)
                    .addComponent(lableImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToChooseImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lalImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(createTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        AdminForm adminForm = new AdminForm();
        adminForm.setVisible(true);
        dispose();        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void inputAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAmountActionPerformed

    private void btnToChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToChooseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select an Image");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File("C:\\Users\\user\\Pictures"));

        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected Image: " + selectedFile.getAbsolutePath());

            // Display image in JLabel (if you have one)
            ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image fileImage = imageIcon.getImage();

            BufferedImage bufferedImage = new BufferedImage(fileImage.getWidth(null), fileImage.getHeight(null), BufferedImage.TYPE_INT_RGB);
            bufferedImage.getGraphics().drawImage(fileImage, 0, 0, null);

            ByteArrayOutputStream convertToByte = new ByteArrayOutputStream();

            try {
                ImageIO.write(bufferedImage, "jpg", convertToByte);

                byte[] file = convertToByte.toByteArray();
                createRequest.setPicture(file);

            } catch (IOException ex) {
            }

            lalImage.setText(imageIcon.toString());

    }//GEN-LAST:event_btnToChooseImageActionPerformed
    }

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        // Get Date
        Date selectedDate = dateChooser.getDate();
        if(selectedDate == null){
            System.out.println("Error :: Date is null");
            return;
        }
        
        Timestamp timestamp = new Timestamp(selectedDate.getTime());

        // Get Amount
        Double amount = 0.00;
        try{
            amount = Double.valueOf(inputAmount.getText().trim());
        }catch(NumberFormatException e){
            System.out.println("Invalid amount format! Please enter a valid mumber.");
        }

        // Get Description
        String description = inputDescription.getText();

        // Get Staff
        String staffId = staff.getId();

        // Get Picture
        byte[] picture = createRequest.getPicture();

        String url = "jdbc:mysql://localhost:3306/db_java_v1";
        String userDb = "root";
        String passDb = "";

        String query = "INSERT INTO expense (date, description, amount, picture, s_id) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, userDb, passDb); PreparedStatement stmt = conn.prepareStatement(query)) {

            // Set parameters
            stmt.setTimestamp(1, timestamp);
            stmt.setString(2, description);
            stmt.setDouble(3, amount);
            stmt.setBytes(4, picture); 
            stmt.setString(5, staffId);
            

            // Execute the insert
            int rowsInserted = stmt.executeUpdate();

            if (rowsInserted > 0) {
                System.out.println("Expense record inserted successfully!");
                JOptionPane.showMessageDialog(null, "Expense Created!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                System.out.println("Failed to insert expense record.");
                JOptionPane.showMessageDialog(null, "Expense Failed", "Failed", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        System.out.println(timestamp + " :: " + amount + " :: " + description + " :: " + staffId + " :: " + createRequest.getPicture());
    }//GEN-LAST:event_btnCreateActionPerformed

    private void inputStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStaffActionPerformed
        // TODO add your handling code here:

        String selectedItem = (String) inputStaff.getSelectedItem();

        System.out.println("User has been selected : " + selectedItem);

        String url = "jdbc:mysql://localhost:3306/db_java_v1";
        String userDb = "root";
        String passDb = "";

        String query = "SELECT s_id FROM staff WHERE s_name=?";

        try (
                Connection cont = DriverManager.getConnection(url, userDb, passDb); PreparedStatement stmt = cont.prepareStatement(query)) {

            stmt.setString(1, selectedItem);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                String id = rs.getString("s_id");
                System.out.println("USER ID - " + id);
                staff.setId(id);
            } else {
                System.out.println("No matching staff found.");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_inputStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnToChooseImage;
    private javax.swing.JLabel createTitle;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextField inputAmount;
    private javax.swing.JTextArea inputDescription;
    private javax.swing.JComboBox<String> inputStaff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel lableImage;
    private javax.swing.JLabel lableStaff;
    private javax.swing.JLabel lalImage;
    // End of variables declaration//GEN-END:variables
}
