/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expense_management.java;

import config.DatabaseConfig;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public final class StaffForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public StaffForm() {
        initComponents();
        getAllStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        title = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        btnCreateNewStaff = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        expenseMenu = new javax.swing.JMenuItem();
        actionMenu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 900));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("WELCOME STAFF");

        desc.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        desc.setForeground(new java.awt.Color(255, 0, 0));
        desc.setText("*** You are login as user Admin. You can use CRUD Operator to Create, Read, Update, and Delete user expense records. Thank you!");

        btnCreateNewStaff.setBackground(new java.awt.Color(0, 255, 51));
        btnCreateNewStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNewStaff.setText("Add New Staff");
        btnCreateNewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewStaffActionPerformed(evt);
            }
        });

        staffTable.setBackground(new java.awt.Color(255, 255, 255));
        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Staff Name", "Position", "Username"
            }
        ));
        staffTable.setRowHeight(50);
        staffTable.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(staffTable);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");

        btnDeleteStaff.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStaff.setText("Delete");
        btnDeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStaffActionPerformed(evt);
            }
        });

        jMenu2.setText("Services");

        jMenuItem1.setText("Product");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        expenseMenu.setText("Expense");
        expenseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseMenuActionPerformed(evt);
            }
        });
        jMenu2.add(expenseMenu);

        jMenuBar1.add(jMenu2);

        actionMenu.setText("Actions");
        actionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuActionPerformed(evt);
            }
        });

        logoutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutMenu.setText("Logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        actionMenu.add(logoutMenu);

        jMenuBar1.add(actionMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addComponent(desc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateNewStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteStaff)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewStaff)
                    .addComponent(jButton1)
                    .addComponent(btnDeleteStaff))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewStaffActionPerformed
        // TODO add your handling code here:
        CreateStaffForm createStaffForm = new CreateStaffForm();
        createStaffForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCreateNewStaffActionPerformed

    private void btnDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffActionPerformed
        // TODO add your handling code here:
        int row = staffTable.getSelectedRow();

        if (row != -1) {

            int columnCount = staffTable.getColumnCount();
            Object[] data = new Object[columnCount];

            for (int i = 0; i < columnCount; i++) {
                data[i] = staffTable.getValueAt(row, i);
            }

            String getStaff = (String) data[3];

            System.out.println(getStaff);

            String sql = "DELETE FROM staff WHERE username = ?";

            try {
                Connection conn = DatabaseConfig.getConnection();

                PreparedStatement pst = conn.prepareStatement(sql);
                
                pst.setString(1, getStaff);
                
                
                int confirmed = JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to delete this staff ?",
                        "Delete Confirmation",
                        JOptionPane.YES_NO_OPTION
                );
                
                if(confirmed == JOptionPane.YES_OPTION){
                    pst.executeUpdate();
                    getAllStaff();
                }
                
            } catch (SQLException e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_btnDeleteStaffActionPerformed

    private void actionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_actionMenuActionPerformed

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void expenseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseMenuActionPerformed
        // TODO add your handling code here:
        AdminForm adminForm = new AdminForm();
        adminForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_expenseMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ProductForm productForm = new ProductForm();
        productForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void getAllStaff() {

        String sql = "SELECT * FROM staff WHERE role = 'user'";

        try {
            Connection conn = DatabaseConfig.getConnection();

            PreparedStatement pst = conn.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();

            DefaultTableModel table = (DefaultTableModel) staffTable.getModel();

            table.setColumnIdentifiers(new Object[]{"No", "Staff Name", "Position", "Username"});

            table.setNumRows(0);

            int i = 1;

            while (rs.next()) {

                Object[] row = {
                    i++,
                    rs.getString("s_name"),
                    rs.getString("position"),
                    rs.getString("username")
                };

                table.addRow(row);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionMenu;
    private javax.swing.JButton btnCreateNewStaff;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JLabel desc;
    private javax.swing.JMenuItem expenseMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JTable staffTable;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
