package expense_management.java;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class UserForm extends javax.swing.JFrame {

    private final String staffId;

    public UserForm(String staffId) {
        this.staffId = staffId;
        initComponents();
        System.out.println("ID from login: " + staffId);
        getStaffExpense();
    }

    public UserForm() {
        this.staffId = "unknown";
        initComponents();
    }

    public void getStaffExpense() {

        System.out.println("Fetching expenses for staff ID: " + staffId);

        String url = "jdbc:mysql://localhost:3306/db_java_v1";
        String userDb = "root";
        String passDb = "";

        try (Connection cont = DriverManager.getConnection(url, userDb, passDb)) {

            String query = "SELECT date, description, amount, picture FROM expense WHERE s_id=?";
            PreparedStatement stmt = cont.prepareStatement(query);
            stmt.setString(1, staffId);

            DefaultTableModel tableModel = (DefaultTableModel) userExpenseTable.getModel();

            tableModel.setColumnIdentifiers(new Object[]{"No", "Date", "Description", "Amount", "Picture"});

            ResultSet rs = stmt.executeQuery();

            tableModel.setRowCount(0);

            int i = 1;

            while (rs.next()) {

                InputStream streamImage = rs.getBinaryStream("picture");
                ImageIcon imageIcon = null;

                try {
                    if (streamImage != null) {
                        BufferedImage image = ImageIO.read(streamImage);

                        int oWidth = image.getWidth();
                        int oHeight = image.getHeight();

                        int nHeight = 50;
                        int nWidth = (int) ((double) nHeight / oHeight * oWidth);

                        imageIcon = new ImageIcon(image);

                        Image img = imageIcon.getImage();
                        Image resize = img.getScaledInstance(nWidth, nHeight, Image.SCALE_SMOOTH);
                        imageIcon = new ImageIcon(resize);
                    }

                } catch (IOException ex) {
                    Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                Object[] row = {
                    i++,
                    rs.getDate("date"),
                    rs.getString("description"),
                    "$\u00A0" + rs.getDouble("amount"),
                    imageIcon
                };
                tableModel.addRow(row);
            }
            userExpenseTable.getColumnModel().getColumn(4).setCellRenderer(new ImageRender());
            userExpenseTable.setFocusable(false);
            userExpenseTable.setCellSelectionEnabled(false);
            userExpenseTable.setColumnSelectionAllowed(false);
            userExpenseTable.setRowSelectionAllowed(false);

        } catch (SQLException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        tablePanelForUser = new javax.swing.JScrollPane();
        userExpenseTable = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("WELCOME USER");

        desc.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        desc.setForeground(new java.awt.Color(255, 0, 0));
        desc.setText("*** User exspence records");

        tablePanelForUser.setAlignmentX(0.0F);
        tablePanelForUser.setAlignmentY(0.0F);

        userExpenseTable.setBackground(new java.awt.Color(255, 255, 255));
        userExpenseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Date", "Description", "Amount", "Picture"
            }
        ));
        userExpenseTable.setRowHeight(50);
        userExpenseTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        userExpenseTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablePanelForUser.setViewportView(userExpenseTable);

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanelForUser, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(title))
                .addGap(12, 12, 12)
                .addComponent(desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanelForUser, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            UserForm userForm = new UserForm("unknown");
            userForm.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel desc;
    private javax.swing.JScrollPane tablePanelForUser;
    private javax.swing.JLabel title;
    private javax.swing.JTable userExpenseTable;
    // End of variables declaration//GEN-END:variables
}
